stages:
  - test

jewish-date:
  stage: test
  image: mysql:5.7
  variables:
    MYSQL_ALLOW_EMPTY_PASSWORD: 1
    MYSQL_DATABASE: db1
    MYSQL_INITDB_SKIP_TZINFO: 1
  before_script:
    - while true; do
      mysql -u root --batch --database db1 --execute 'SELECT 1; && break;
      sleep 1;
      done;
  script:
    - bash ./tests/run-tests.sh
