name: MySQL tests
on: push
jobs:
  jewish-date:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      COMPOSE_FILE: ./tests/docker-compose.yml
      MYSQL_CMD: docker compose exec mysql mysql
    steps:
      - uses: actions/checkout@v3
      - run: docker compose up -d
      - run: docker container inspect mysql
      - run: docker compose exec mysql ls -la /docker-entrypoint-initdb.d/
      - run: |
          while true; do
            $MYSQL_CMD -u root --batch --database db1 --execute 'SELECT 1;' && break;
            sleep 1;
            done;
      - run: bash ./tests/hebrewcalendar/jewish-date/run-tests.sh
      - run: docker compose down
