name: MySQL tests
on: push
jobs:
  jewish-date:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      COMPOSE_FILE: ./tests/docker-compose.yml
      MYSQL_CMD: docker compose exec mysql mysql
      MYSQL_DATABASE: db1
    steps:
      - uses: actions/checkout@v3
      - name: Start MySQL
        run: docker compose up -d
      - name: Wait for MySQL
        run: |
          while true; do
            $MYSQL_CMD -u root --batch --database $MYSQL_DATABASE --execute 'SELECT 1;' && break;
            sleep 1;
            done;
      - name: Run unit tests
        run: bash ./tests/hebrewcalendar/jewish-date/run-tests.sh
      - name: Shut down MySQL
        run: docker compose down
