name: MySQL tests
on: push
jobs:
  jewish-date:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - run: docker compose -f ./tests/docker-compose.yml up -d
      - run: |
          while true; do
            docker exec mysql mysql -u root --batch --database db1 --execute 'SELECT 1;' && break;
            sleep 1;
            done;
      - run: bash $GITHUB_WORKSPACE/tests/hebrewcalendar/jewish-date/run-tests.sh
        env:
          MYSQL_CMD: docker exec mysql mysql
      - run: docker compose down
